name: LaTeX Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  LatexBuild:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install latexmk
        run: |
          sudo apt-get update
          sudo apt-get install -y latexmk

      - name: Build LaTeX
        id: build-latex
        run: |
          latexmk -pdf -interaction=nonstopmode -f main.tex
        continue-on-error: true
        
      - name: Build log results
        run: |
          cat main.log

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: curriculum-pdf
          path: main.pdf
        if: steps.build-latex.outcome == 'success'
