name: LaTeX Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install latexmk
        run: |
          sudo apt-get update
          sudo apt-get install -y latexmk

      - name: Set up LaTeX        
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
           main.tex
           education.tex
           professional_experiance.tex

      - name: Build LaTeX
        run: |
          latexmk -pdf -interaction=nonstopmode main.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: curriculum-pdf
          path: main.pdf
