name: LaTeX Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  LatexBuild:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install latexmk
        run: |
          sudo apt-get update
          sudo apt-get install -y latexmk

      - name: Build LaTeX
        id: build-latex
        run: |
          latexmk -pdf -interaction=nonstopmode -f main.tex
        continue-on-error: true
        
      - name: Build log results
        run: |
          cat main.log

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: curriculum-pdf
          path: main.pdf
        if: steps.build-latex.outcome == 'success'


  Release:
    needs: LatexBuild
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          body: |
            This is the release for the curriculum PDF.
          draft: false
          prerelease: false

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v2
        with:
          name: curriculum-pdf
          path: main.pdf
        if: steps.create_release.outputs.release_id
